# Generated by Django 5.2.4 on 2025-09-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artmodel',
            name='email',
            field=models.EmailField(blank='False', max_length=254),
        ),
        migrations.AlterField(
            model_name='artmodel',
            name='password',
            field=models.CharField(blank='False', max_length=50),
        ),
    ]
