# Generated by Django 5.2.4 on 2025-09-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artApp', '0002_alter_artmodel_email_alter_artmodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='artmodel',
            name='description',
            field=models.TextField(blank='True', null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='artmodel',
            name='price',
            field=models.DecimalField(blank='False', decimal_places=2, max_digits=100000, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='artmodel',
            name='title',
            field=models.CharField(blank='False', max_length=250),
        ),
    ]
