# Generated by Django 5.2.4 on 2025-09-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artApp', '0003_artmodel_description_artmodel_price_artmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='artmodel',
            name='password',
        ),
    ]
